### ISSUE TITLE
create keyed json

### ISSUE THREAD

**Issue by emmaireti** [adi20raj/CSV2JSON#1]
Hi @adi20raj, i'm trying to use your converter to convert CSV to json with multiple events based on the same keyed field.  can you help with the right customization for the code. see sample below:

container,container_iso_code,events[0].event_code,events[0].event_name,events[0].remarks,events[0].date,provider
AMFU1234567,45G1,EXO1,Unit Available,OPR,2021-12-01 16:16:17.000,providerA
AMFU1234567,45G1,EXO4,Scheduled for Transfer,OPR,2021-12-02 08:28:04.000,providerA

**expected result:**

[
   {
		"container": "AMFU1234567",
		"container_iso_code": "45G1",
		"events": [
			{
				"date": "2021-12-01 16:16:17.000",
				"event_code": "EXO1",
				"event_name": "Unit Available",
				"remarks": "OPR"
			},
                         {
				"date": "2021-12-02 08:28:04.000",
				"event_code": "EXO4",
				"event_name": "Scheduled for Transfer",
				"remarks": "OPR"
			}
		],
		"provider": "providerA"
   }
]

**Comment by adi20raj** [comment]
Hi @emmaireti Can you try [multi-level array example](https://github.com/adi20raj/CSV2JSON#multi-level-array-with-internal-objects) for your use case. Instead of multiple entries, all internal objects should be part of one CSV data row.
